name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            packages: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            packages: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            packages: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            packages: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            packages: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            packages: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            packages: gcc-aarch64-linux-gnu
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            packages: gcc-arm-linux-gnueabihf
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            packages: gcc-multilib
          - os: windows-latest
            target: i686-pc-windows-msvc
            packages: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            packages: musl-tools
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            packages: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            packages: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install cross toolchains
      if: runner.os == 'Linux' && matrix.packages != ''
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.packages }}

    - name: Build release
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pacm-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/pacm*

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run tests with coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: lcov.info
        fail_ci_if_error: false